config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  get 'receipt' => 'pages#receipt'
  get 'faq' => 'pages#faq'
  get 'privacy_and_terms' => 'pages#privacy_and_terms'
  get 'orders' => 'orders#index'
  get 'contact_us' => "pages#contact_us"
  get 'new_order' => 'orders#new'
  get 'order' => 'order#show'
  get 'why_us' => 'pages#why_us'
  get 'how_we_maintain_quality' => 'pages#how_we_maintain_quality'
  get 'learn_more_about_responsive_redesigns' => 'pages#learn_more_about_responsive_redesigns'
  get 'pricing' => 'pages#pricing'
  get 'submission_confirmation' => 'pages#submission_confirmation'

end

app/models/order.rb
class Order < ActiveRecord::Base

	ORDER_TYPES = ["Quick responsive design of an existing site",
		"New website design (not a redesign)",
		"Full, custom web application",
		"Mobile application",
		"Other"]
		
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

	def index
	end

	def new 
		@order = Order.new
	end

	def create
		@order = Order.new(order_params)

		if @order.save
			format.html { render :show}
		else
			format.html { render :new }
		end
	end 

	def show 
		# show the receipt from the order
	end

private
	
	def order_params
		params.require(:order).permit(:contact_name, :contact_company_name, :contact_email, :contact_phone_number, :project_type, :project_name, :project_timeline, :additional_comments, :text_preferred, :preference_no_call)
	end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end

  def faq
  end

  def contact_us
  end

  def privacy_and_terms
  end

  def why_us
  end

  def how_we_maintain_quality
  end

  def pricing
  end

  def submission_confirmation
  end

  def learn_more_about_responsive_redesigns
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_agile_tracking_code.html.erb
<script id="_agile_min_js" async type="text/javascript" src="https://responsiveredesign.agilecrm.com/stats/min/agile-min.js"> </script>
<script type="text/javascript" >
var Agile_API = Agile_API || {}; Agile_API.on_after_load = function(){
_agile.set_account('sm9g13umrh80rqp5md144hmoq1', 'responsiveredesign');
_agile.track_page_view();
_agile_execute_web_rules();};
</script>

app/views/layouts/_contact_us_modal_text.html.erb
    <!-- below is for modal inner text -->
    <div class="modal fade" id="contactUsModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title" id="myModalLabel">Contact Us Directly</h4>
          </div>
          <div class="modal-body text-center black-text">
	        <p>Phone: <span class="orange">917.727.7206</span><br>
            Yes, we text.</p>

    			<p>or</p>
    			<p>Email: <span class="orange">code@responsiveredesign.io</span></p>
             
     
          </div>
          <div class="modal-footer">
            <p>We welcome your feedback!</p>
            <!-- <button type="button" class="btn btn-warning">Sign up!</button> -->
          </div>
        </div>
      </div>
    </div>
    <!-- above is for modal inner text -->

app/views/layouts/_drop_arrows.html.erb
<span class="before-toggle">
	<i class="fa fa-angle-down" aria-hidden="true"></i>
</span>
<span class="after-toggle">
	<i class="fa fa-angle-up" aria-hidden="true"></i>
</span>

app/views/layouts/_footer.html.erb
<footer>
	<h4 class="footer-logo"><%= link_to root_path do %>
			<%= image_tag('rr-logo-white.png', class: "footer-logo-image") %>
		<% end %>
		<p class="hidden">Responsive Redesign</p>
	</h4>

	<div class="row">
		<div class="col-md-4">
			<p>	
				<!-- social media -->
				<!-- todo when our social media is good-looking, insert render of social media layout -->
			</p>
		</div>
		<div class="col-md-4 gray">
			<p>
				<%= link_to "About", root_path %>
			</p>
			<p>
				<%= link_to "Learn", learn_more_about_responsive_redesigns_path %>
			</p>			
			<p>
				<%= link_to "Quality", how_we_maintain_quality_path %>
			</p>
			<p>
				<%= link_to "Pricing", pricing_path %>
			</p>
			<!-- input faq page? -->
			<p>
				<%= link_to 'Order a Redesign', contact_us_path, class: "un-button" %>
			</p>
			<br>
		</div>
		<div class="col-md-4">
			<!-- social media inputting here, once we have enough social stuff worth following -->
			<!-- <button class="un-button" data-toggle="modal" data-target="#newsletterModal">Sign up for our Newsletter</button></p> -->
		</div>
	</div>
</footer>

app/views/layouts/_home_page_cover_video.html.erb
<!-- begin text from coverr for cover video -->
<div class="homepage-hero-module">
    <div class="video-container">
        <div class="filter"></div>
        <video autoplay loop class="fillWidth">
            <source src="https://s3.us-east-2.amazonaws.com/rrbrandvideos/Workaholic.mp4" type="video/mp4" />Your browser does not support the video tag. I suggest you upgrade your browser.
            <source src="https://s3.us-east-2.amazonaws.com/rrbrandvideos/Workaholic.webm" type="video/webm" />Your browser does not support the video tag. I suggest you upgrade your browser.
        </video>
        <div class="poster hidden">
            <img src="https://s3.us-east-2.amazonaws.com/rrbrandimages/Workaholic.jpg" alt="keyboard workaholic web design">
        </div>
    </div>
</div>
<!-- end cover video added text -->

app/views/layouts/_index_page_1.html.erb
<!-- this is the older (than June 2018) design for the home page. Talks more about responsive design than about us as a company.  
BEGIN NOW -->

<div class="banner-image-area animated fadeIn delay-09s wow">
    <div id="index-banner-text-group">
        <h1 class="banner-text-1 animated fadeInDown delay-07s">Mobile&nbsp;Responsive,</h1>
        <h1 class="banner-text-2 animated fadeInDown delay-07s">Custom&nbsp;Websites</h1>
        <h3 class="text-center free-offer">Now offering a free 15 minute <br>consulting session about ANYTHING internet,<br> <small class="orange">(not just about how we can work together)</small>.</h3>
        <div class="text-center animated fadeInDown delay-07s" id="index-action-button">
            <%= link_to "Text Us Now", contact_us_path, class: "btn btn-lg btn-default" %>
        </div>
    </div><!-- index banner text group -->
    <div class="banner-image-area-overlay">
    </div>
</div><!-- end banner image area -->
<!-- coverr video layout could render here if we wanted to use it -->
<section>
    <div class="container">
        <div class="text-center animated fadeInUp delay-09s">
            <%= image_tag("flaticons/flaticon-bounce-rate-customized.png", class: "adjusted-left") %>
        </div>    
        <h2>We Will Fix Your Bounce Rate!</h2>
        <h3>Bounce Rate<br> =<br> "the percentage of visitors who come to your website and leave<br> without viewing any other pages on your website"</h3>
        <p class="text-center">a.k.a. How quickly Millenials leave when a website is ugly or doesn't answer their question within 3 seconds.</p>
        <div class="text-center">
            <%= link_to "Get a Beautiful Website, Fast", contact_us_path, class: "btn btn-default btn-lg" %>    
        </div>
    </div><!-- end container -->
</section>
<section class="background-alt-color" alt="characteristics of mobile optimized and mobile responsive websites">
    <div class="container animated fadeInUp delay-09s">
        <div class="row">
            <div class="text-center animated fadeInUp delay-09s">
                <%= image_tag("flaticons/phone-storefront-flaticon-combo.png") %>
            </div>            
            <h3>Mobile&nbsp;Optimize Your&nbsp;Company</h3>
            <br>
            <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <p><big>Characteristics of a mobile-optimized brand:</big></p>
                <ul>
                    <h4>Web:</h4>
                    <li>Website is as easy to read on mobile as on desktop</li>
                    <li>All info on the website is current, including the address, phone number, products, and pricing</li>
                    <li>The first page on the website to load offers the exact info that user wants to find</li>
                    <li>Website images render efficiently</li>
                    <li>No mobile pinching is necessary, ever.</li>
                    <li>Drop downs and animations are functional, timely, and not distracting</li>
                    <li>Textual content is brief, and accompanied by skimmable graphics</li>
                    <h4>Non-web:</h4>
                    <li>Synced with Google Maps whenever a physcial location is involved</li>
                    <li>Relevant Google Map searches return the brand <br>&nbsp;&nbsp;(eg. a cafe shows up for "cafe", "coffee", "coffee shop", "brunch", "tea", "pastries", "etc.")</li>
                    <li>Synced with Yelp whenever a physical location is involved</li>
                    <h4>To Sum It Up:</h4>
                    <li>User enjoys being on your site and feels good after interacting with it</li>
                </ul>
            </div><!-- end col -->
            <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <div class="text-center margin-top-on-desktop device-circle-icon">
                    <%= image_tag("device-icon-in-orange-circle.png") %>
                    <!-- icon found for free on https://www.iconfinder.com/websitebeaver -->
                </div>
                <!-- todo insert graphic of phone with mobile site and another with google maps -->
            </div><!-- end col -->
        </div><!-- end row -->
        <br>
        <div class="text-center">
            <%= link_to "View Full Website Standards Checklist", how_we_maintain_quality_path, class: "btn btn-default btn-lg" %>
        </div>
    </div><!-- end container-->
</section>
<section>
    <div class="container text-center animated fadeInUp delay-09s">
        <div class="text-center animated fadeInUp delay-09s">
            <%= image_tag("flaticons/flaticon-price-tag-smashicons.png") %>
        </div>        
        <h3>Pricing</h3>
        <p>Unlike other agencies, we post pricing for our basic services on this website, <br>for you to look at now!</p>
        <div class="text-center">
            <%= link_to "Pricing for a Redesign", pricing_path, class: "btn btn-lg btn-default" %>
        </div>
        <br>
        <p><small>Note: Services in addition to what is listed on this page do require custom rates.</small></p>
    </div>
</section>
<section class="background-alt-color" id="center-main-section" class="text-left animated fadeInUp delay-09s">
    <div class="text-center animated fadeInUp delay-09s">
        <%= image_tag("flaticons/flaticon-faq-freepik.png") %>
    </div>
    <h3 class="text-center orange animated fadeInUp delay-09s">Frequently Asked Questions</h3>
    <div class="row animated fadeInUp delay-03s">
        <div class="common-questions col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
            <br>
            <div class="explanation">
                <p class="short-form-question">What is responsive design?</p><p class="short-form-answer">Web design that looks good on any device at any width.</p>
                <p class="short-form-question">How fast can it be done?</p><p class="short-form-answer">Average development time = One week.</p>
                <p class="short-form-question">How custom is it?</p><p class ="short-form-answer">In a code editor, with help from our pre-designed, modern templates.</p>
                <p class="short-form-question">Is it affordable?</p><p class ="short-form-answer">We think so. Our prices are often 30% below other American agencies.
                <p class="short-form-question">Is it up to date?</p><p class ="short-form-answer">We code from scratch and use HTML5, CSS3, jQuery, Bootstrap, and our own custom templates.</p>
                <p class="short-form-question">Where is it made?</p><p class ="short-form-answer">We are headquartered in New York City.</p>
                <p class="short-form-question">What kind of service do I get?</p><p class ="short-form-answer">Our founder is available by appointment and would love to speak with you.</p>
            </div>            
            <div class="text-center">
                <%= link_to "Order A Website Now", contact_us_path, class: "btn btn-default btn-lg" %>
            </div>            
        </div>
    </div><!-- end .row -->
</section><!-- end #center-main-section -->

app/views/layouts/_index_page_2.html.erb
<!-- this is the index page made during June 2018. This page talks more about us as a company rather than about responsive design in general. Consider using soem of the old content for educational materials.  Maybe we have a "Learn" page with a grid of articles, and content from there is one of the articles. 

BEGIN NOW -->

<div class="banner-image-area animated fadeIn delay-09s wow">
    <div class="background-image-container">
        <%= image_tag ('gplaypattern.png') %>
    </div>
    <div id="index-banner-text-group">
        <h1 class="banner-text-1 animated fadeInDown delay-07s">Mobile&nbsp;Responsive,</h1>
        <h1 class="banner-text-2 animated fadeInDown delay-07s">Custom&nbsp;Websites</h1>
        <h3 class="text-center free-offer">User Interaction &amp; Web Design Firm <br>with Extensive Startup Experience</h3>
        <div class="text-center animated fadeInDown delay-07s" id="index-action-button">
            <%= link_to "Text Us Now", contact_us_path, class: "btn btn-lg btn-default" %>
        </div>
    </div><!-- index banner text group -->
    <div class="banner-image-area-overlay">
    </div>
</div><!-- end banner image area -->
<!-- coverr video layout could render here if we wanted to use it -->
<section class="text-left animated fadeInUp delay-09s">
    <div class="container">
        <div class="text-center">
            <%= image_tag 'flaticons/writing-book-with-pen.png' %>
        </div>
        <h3 class="text-center orange animated fadeInUp delay-09s">The Code Book</h3>
        <div class="row animated fadeInUp delay-03s">
            <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
                <br>
                <div>
                    <p>When this company was first established, all we knew about the business was how to code.  We had no idea how to run a web design and developmenet company. 
                        <larger class="orange">
                            <i>
                                <br><br>How do we price things? 
                                <br>How should we find clients?
                                <br>What will they expect from us?
                                <br>
                            </i>
                        </larger>
                    </p>
                    <p>So we started asking other agencies how they run their businesses.</p>
                    <p>The result is an interview based e-book called <b class="orange">How To Serve: Code</b> that we expect to distribute within the year.</p>
                    
                    
                    <p>This book has given us a unique, investigative, increasingly informed view into the web services industry as a whole.</p>
                    <h4>What this means:</h4>
                    <ol>
                        <li>Our founder now advises other web services companies on best practices, industry trends, and how to grow a sustainable company.</li>
                        <li>Having seen many business strategies play out, we make informed choices about how to best serve you.</li>
                        <li>We have a ton of allies who can do pretty much anything that we cannot directly do ourselves.</li>
                    </ol>
                    <br>
                    <p class="text-center"><i>So...how can the industry help you?</i></p>
                </div>            
                <div class="text-center">
                    <%= link_to "Talk To Us", contact_us_path, class: "btn btn-default btn-lg" %>
                </div>            
            </div>
        </div><!-- end .row -->
    </div><!-- end container -->
</section><!-- end #center-main-section -->
<section class="background-alt-color text-left animated fadeInUp delay-09s">
    <div class="container">
        <div class="text-center animated fadeInUp delay-09s">
            <%= image_tag("flaticons/women-in-code-icon.png") %>
        </div>
        <h3 class="text-center orange animated fadeInUp delay-09s">Supporting Women in Tech</h3>
        <div class="row animated fadeInUp delay-03s">
            <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
                <br>
                <div>
                    <p>As a Millennial &amp; woman-owned tech comany based in the United States, we are aware of our unique opportunity to make a difference in the discussion of gender quality in the in tech industry.</p>
                    <p>As of 2018, Responsive Redesign is developing a Give Back Policy that will use proceeds from each completed project to help women and girls gain access to educational resources that help them learn how to code.</p>
                    <p>We believe that equality starts with being invited to the table, and that education is the best invitation.</p>
                </div>            
                <div class="text-center">
                    <%= link_to "Contact Us To Hear More", contact_us_path, class: "btn btn-default btn-lg" %>
                </div>            
            </div>
        </div><!-- end .row -->        
    </div><!-- end container -->    
</section><!-- end #center-main-section -->
<section class="text-left animated fadeInUp delay-09s">
    <div class="container">
        <div class="text-center animated fadeInUp delay-09s">
            <%= image_tag("flaticons/checklist-flaticon-orange.png", class: "icon-image-sizing") %>
        </div>
        <h3 class="text-center orange animated fadeInUp delay-09s">Quality of Work</h3>
        <div class="row animated fadeInUp delay-03s">
            <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
                <br>
                <div>
                    <p>We have high standards for ourselves individually and professionally, and we maintain high standards for those that we collaborate with.</p>
                    <br>
                    <p class="text-right">If a potential partner doesn't speak English well, if they don't write up to date code, if their previous work is just ugly, we quickly say no to the collaboration.</p>
                    <br>
                    <p>In addition to passing our preliminary tests, every designer or developer we work with receives our custom made Quality Checklist, and we hold them to this standard during every project.</p>
                    <div class="text-center">
                        <%= link_to "See The Checklist", how_we_maintain_quality_path, class: "btn btn-default btn-lg" %>
                    </div>
                </div>                       
            </div><!-- end col -->
        </div><!-- end .row -->        
    </div><!-- end container -->
</section><!-- end #center-main-section -->
<section class="background-alt-color">
    <div class="container text-center animated fadeInUp delay-09s">
        <div class="text-center animated fadeInUp delay-09s">
            <%= image_tag("flaticons/flaticon-price-tag-smashicons.png") %>
        </div>        
        <h3>Pricing</h3>
        <p>Unlike other agencies, we post pricing for our basic services on this website, <br>for you to look at now!</p>
        <div class="text-center">
            <%= link_to "Pricing for a Redesign", pricing_path, class: "btn btn-lg btn-default" %>
        </div>
        <br>
    </div>
</section>
<section class="text-left animated fadeInUp delay-09s">
    <div class="container ">
        <div class="text-center animated fadeInUp delay-09s">
            <%= image_tag("flaticons/icon-customer-story.png", class: "icon-image-sizing") %>
        </div>
        <h3 class="text-center orange animated fadeInUp delay-09s">Our Mission</h3>
        <div class="row animated fadeInUp delay-03s">
            <div class="col-xs-12 col-sm-offset-1 col-sm-10 col-md-offset-2 col-md-8">
                <br>
                <div class="mission-statement-text">
                    Help build a more beautiful and usable internet, <br>and have fun while doing it!
                </div>            
                <div class="text-center">
                    <%= link_to "Let's Work Together", contact_us_path, class: "btn btn-default btn-lg" %>
                </div>            
            </div>
        </div><!-- end .row -->
    </div><!-- end container -->
</section><!-- end #center-main-section -->

app/views/layouts/_nav.html.erb
<nav>
    <h1>
        <%= link_to root_path do %>
            <!-- displays on larger screen sizes -->
            <%= image_tag('rr-logo-white-long-left.png', class: "hidden-xs", id: 'nav-logo-single-row') %>
            <!-- displays on smaller screen sizes -->
            <%= image_tag('rr-logo-white.png', class: "hidden-sm hidden-md hidden-lg", id: 'nav-logo-double-row') %>
            <p class="hidden orange">ResponsiveRedesign.io</p>
        <% end %>
    </h1>
    <div id="xs_hamburger">
        <div id="hamburger_icon">
            <%= image_tag("list-menu.png") %>
        </div>
        <div id="menu_label">Menu</div>
    </div>
    <div id="nav_elements">
        <ul>
            <li><%= link_to "About", root_path %></li>
            <li><%= link_to "Learn", learn_more_about_responsive_redesigns_path %></li>
            <li><%= link_to "Quality", how_we_maintain_quality_path %></li>
            <li><%= link_to "Pricing", pricing_path %></li>
            <!-- input faq page? -->
            <li alt="Order A Design"><%= link_to 'Order', contact_us_path, class: "btn btn-sm btn-success" %></li>
        </ul>
    </div>
</nav>

app/views/layouts/additional_code_components.html.erb
<!-- for code that we may want to use in the future -->

<%= link_to "http://rr-cravath.responsiveredesign.io/", target: "none" do %>
    <p><%= image_tag("flaticons/flaticon-all3responsive-Becris.png", class: "flaticon-tiny-labels") %>
        <!-- icon by Becris and found on flaticon.com -->
        <strong>Example:</strong> Cravath - About the New York Law Firm
    </p>
<% end %><!-- end link to image -->
<div class="portfolio-iframe">
    <iframe width="560" height="315" src="https://www.youtube.com/embed/dNNmLFjh0rg" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div><!-- end portfolio iframe -->

<p><%= image_tag("flaticons/flaticon-all3responsive-Becris.png", class: "flaticon-tiny-labels") %>
            <!-- icon by Becris and found on flaticon.com -->
            <strong>Example:</strong> Giles Marini - About the Actor and Model
        </p>
    <!-- end link to site -->
    <div class="portfolio-iframe">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/6LktQlgS-lo" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div><!-- end portfolio iframe -->

    <%= link_to "https://www.gymstore.com", target: "none" do %>
        <p><%= image_tag("flaticons/flaticon-all3responsive-Becris.png", class: "flaticon-tiny-labels") %>
            <!-- icon by Becris and found on flaticon.com -->
            <strong>Example:</strong> Gym Store - A full e-eommerce store
        </p>
    <% end %><!-- end link to site -->
    <div class="portfolio-iframe">
        <!-- insert video here -->
    </div><!-- end portfolio iframe -->

    <%= link_to "http://www.consciousoffice.io/", target: "none" do %>          
        <p><%= image_tag("flaticons/flaticon-all3responsive-Becris.png", class: "flaticon-tiny-labels") %>
            <!-- icon by Becris and found on flaticon.com -->
            <strong>Example:</strong> Conscious Office - Custom ecommerce storefront
        </p>
    <% end %><!-- end link to site -->
    <div class="portfolio-iframe">
        <iframe width="560" height="315" src="https://www.youtube.com/embed/zRM2OWK6cAk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
    </div><!-- end portfolio iframe -->


<section id="why-responsive">
    <div class="row">
        <div class="lighter-background-1 full-width-area">
            <h3>Static&nbsp;Websites Damage&nbsp;Sales</h3>
            <br>
            <div class="paragraph-fact">
                <p><span class="funky-font-styling">55%</span><br> 
                    of all e-commerce interactions <br>
                    take place on smartphones</p>
            </div><!-- end .paragraph-text -->
            <div class="paragraph-fact">
                <p><span class="funky-font-styling">69%</span><br> of customers prefer to order online <br>than over the phone </p>
            </div><!-- end .paragraph-text -->
            <div class="paragraph-fact">                
                <p><span class="funky-font-styling">50%</span><br> of customers
                    actually leave a site <br>
                    when they see it's<br> 
                not mobile responsive</p>
            </div><!-- end .paragraph-text -->
            <div class="paragraph-fact">
                <p><span class="funky-font-styling">1&nbsp;/&nbsp;3</span><br> 
                    of customers
                    abandon a purchase <br>
                    due to the annoyance <br>
                    of static sites</p>
            </div><!-- end .paragraph-text -->
        </div>
        <div class="lighter-background-2 full-width-area">
            <h3>Benefits&nbsp;Of Responsive&nbsp;Websites</h3>
            <br>
            <span class="near-white">
                <div class="paragraph-fact lean-left">
                    <p>Reduce your <br>
                        <span class="funky-font-styling-2">bounce rate</span> <br>
                        to less than 20%</p>
                </div><!-- end .paragraph-text -->
                <div class="paragraph-fact lean-right">
                    <p>Customers see you <br>
                        as a <span class="funky-font-styling-2">modern</span> company.</p>
                </div><!-- end .paragraph-text -->
                <div class="paragraph-fact lean-left">                
                    <p>Customers can interact <br>
                        with you <span class="funky-font-styling-2">impulsively</span>, <br>
                        wherever they are.</p>
                </div><!-- end .paragraph-circle -->
            </span><!-- end span.near-white -->
        </div><!-- end .col -->
    </div><!-- end .row -->
</section><!-- end #why-responsive -->
<!-- -->

<li>
    <h3>Rapid Redesign</h3>
    <p>We build your new website from scrach, with a little help from our own customized code templates.</p>
    <p><strong>The outcome:</strong> You have a new, customized, mobile responsive simple website.</p>
    <p><i>Since we know the code so well, this can often happen with one week's development time.</i></p>
    <p><%= image_tag("flaticons/flaticon-price-tag-smashicons.png", class: "flaticon-tiny-labels") %>
        <strong>Rate:</strong> Flat rate, base price often ranges from between $2,000 USD to $5,000 USD.</p>
    <p><%= image_tag("flaticons/flaticon-alarm-clock-smashicons.png", class: "flaticon-tiny-labels") %>
        <!-- icon made by Smashicons, found on flaticons.com -->
        <strong>Timing:</strong> Typcially, 1 week of development.</p>
    <%= link_to "http://rr-cybex.responsiveredesign.io/", target: "none" do %>
        <p><%= image_tag("flaticons/flaticon-all3responsive-Becris.png", class: "flaticon-tiny-labels") %>
            <!-- icon by Becris and found on flaticon.com -->
            <strong>Example:</strong> Cybex - A simple e-commerce front end website</p>

<!--                <div class="portfolio-image-section">
            todo insert example links and images
        </div> -->
    <% end %><!-- end link to -->
    <div class="text-center">
        <%= link_to "Order A Rapid Redesign", contact_us_path, class: "btn btn-default btn-lg" %>
    </div><!-- end .text-center with button -->
</li>

<!-- not used area follows from here -->
<div class="banner-area hidden"> 
    <div class="opaque-overlay">
        <div class="inner-container">
            <div class="hotwords-container">
                <p>Mobile Friendly | 
                Rapid&nbsp;Development | 
                High&nbsp;Quality | 
                Modern&nbsp;Code |
                Affordable
                <h2 class="banner-text">Mobile&nbsp;Responsive, Custom&nbsp;Websites</h2>
                <h2 class="banner-text orange hidden">Built&nbsp;By&nbsp;Web&nbsp;Designers You&nbsp;Can&nbsp;Trust</h2>
                Integrity | 
                Modern&nbsp;Web&nbsp;Design | 
                Design&nbsp;In&nbsp;A&nbsp;Week | 
                Your&nbsp;Brand | 
                Custom&nbsp;Design |  
                Raw&nbsp;Code | 
                Make&nbsp;It&nbsp;Yours
                </p>
            </div>        
            <span class="hidden-lg hidden-md hidden-sm"><br></span>
        </div><!-- end .inner-container so that we can have padding on the rest of it -->
    </div>
    <!-- end .opaque-overlay -->
</div><!-- end .banner-area -->
<!-- end unused banner area -->

app/views/pages/index.html.erb
<!-- provide custom subtitle for each page -->
<% content_for(:subtitle) do %>Mobile Responsive Web Design and Development<% end %>

<%= render 'layouts/index_page_2' %>